# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit, prepare-commit-msg]
repos:
- repo: https://github.com/pdm-project/pdm
  rev: 2.9.3 # a PDM release exposing the hook
  hooks:
    - id: pdm-export
      args: ['-o', 'requirements.txt', '--without-hashes']
      files: ^pdm.lock$
    - id: pdm-lock-check

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-merge-conflict
  - id: requirements-txt-fixer
