[project]
name = "trapper-script"
version = "0.3.0"
description = ""
authors = [
    {name = "GuGuMur", email = "2221533105@qq.com"},
]
dependencies = [
    "mwbot>=1.0.27",
    "fastapi==0.95.2",
    "mwparserfromhell>=0.6.5",
    "httpx>=0.25.0",
    "jinja2>=3.1.2",
    "loguru>=0.7.2",
    "uvicorn[standard]==0.22.0",
    "python-multipart>=0.0.6",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}
