name: edit
on:
  release:
    types:
        - published
  push:
    branches:
        - main
jobs:
  pypi-publish:
    name: Upload JS to PRTS
    runs-on: ubuntu-latest
    environment: release
    permissions:
        id-token: write
    steps:

      - uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
      # You are now able to use PDM in your workflow
      - name: Install dependencies
        run: pdm install
      - name: Edit page
        run: pdm run python script/update.py ${{ secrets.PRTS_BOT_TOKEN }}
